# Generated by Django 3.1.7 on 2021-03-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_dislike_like_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dislike",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="%Y-%m-%d"),
        ),
        migrations.AlterField(
            model_name="dislike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dislikes",
                to="network.post",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="%Y-%m-%d"),
        ),
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="network.post",
            ),
        ),
    ]
